# Generated by Django 4.1.3 on 2023-07-12 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.BigAutoField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden_pedido', models.CharField(max_length=14, null=True)),
                ('descripcion', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('repartidor', models.IntegerField(null=True)),
                ('fk_id_estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('imagen_producto', models.ImageField(default='images/Not_found.png', null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
                ('descripcion', models.CharField(max_length=400)),
                ('prod_is_active', models.BooleanField(default=True)),
                ('row_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Relacionado',
            fields=[
                ('id_relacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField()),
                ('id_producto_relacionado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('rut_proveedor', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('prov_is_active', models.BooleanField(default=True)),
                ('row_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=30)),
                ('fk_id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permiso')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_usuario', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('celular', models.IntegerField()),
                ('u_is_active', models.BooleanField(default=True)),
                ('row_status', models.BooleanField(default=True)),
                ('fk_id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
                ('fk_id_rol', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_solicitud', models.IntegerField(null=True)),
                ('estado', models.CharField(max_length=50)),
                ('realizado_por', models.CharField(max_length=50, null=True)),
                ('fk_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('fk_id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboPedido',
            fields=[
                ('id_ReciboPedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('fk_id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
                ('fk_id_productos', models.ManyToManyField(to='core.producto')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='fk_id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fk_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('producto', models.IntegerField(null=True)),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
