# Generated by Django 4.1.3 on 2023-05-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='apellido_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
