# Generated by Django 4.1.3 on 2023-07-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_relacionado',
            name='p_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
