# Generated by Django 4.1.3 on 2023-06-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibopedido',
            name='fk_id_estado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fk_id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
            preserve_default=False,
        ),
    ]
