# Generated by Django 4.1.3 on 2023-05-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_carrito_fk_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='fk_id_producto',
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.IntegerField(null=True),
        ),
    ]
