# Generated by Django 4.1.3 on 2023-06-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pedido_estado_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagenProd',
            new_name='imagen_producto',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fk_id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
    ]
