# Generated by Django 4.1.3 on 2023-05-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_carrito_fk_id_producto_carrito_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clave',
        ),
    ]
