# Generated by Django 4.1.3 on 2023-06-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_imagenprod_producto_imagen_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='repartidor',
            field=models.IntegerField(null=True),
        ),
    ]
