# Generated by Django 4.1.3 on 2023-06-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_repartidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='orden_pedido',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
