# Generated by Django 4.1.3 on 2023-05-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_usuario_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
