# Generated by Django 4.1.3 on 2023-05-18 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_carrito_fk_id_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
    ]
