# Generated by Django 4.1.3 on 2023-05-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_carrito_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenProd',
            field=models.ImageField(null=True, upload_to='productos', verbose_name='Imagen del Producto'),
        ),
    ]
