# Generated by Django 4.1.3 on 2023-05-23 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_producto_imagenprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='fk_id_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagenProd',
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='row_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='row_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='row_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_solicitudes', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('fk_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('fk_id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
