# Generated by Django 4.1.3 on 2023-05-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_is_active_producto_prod_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenProd',
            field=models.ImageField(null=True, upload_to='productos', verbose_name='Imagen del Producto'),
        ),
    ]
