# Generated by Django 4.1.3 on 2023-05-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_producto_imagenprod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitudes',
            new_name='Solicitud',
        ),
    ]
