# Generated by Django 4.1.3 on 2023-05-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_solicitudes_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='id_solicitudes',
            new_name='id_solicitud',
        ),
    ]
