# Generated by Django 4.1.3 on 2023-05-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_id_solicitudes_solicitud_id_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cantidad_solicitud',
            field=models.IntegerField(null=True),
        ),
    ]
