# Generated by Django 4.2 on 2023-05-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_solicitud_fk_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenProd',
            field=models.ImageField(default='images/Not_found.png', null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
    ]
