# Generated by Django 4.1.3 on 2023-06-06 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_solicitud_fk_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenProd',
            field=models.ImageField(default='images/Not_found.png', null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
        migrations.CreateModel(
            name='ReciboPedido',
            fields=[
                ('id_ReciboPedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_pedido', models.TextField()),
                ('fk_id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
                ('fk_id_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
