# Generated by Django 4.1.3 on 2023-06-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pedido_total_alter_producto_imagenprod_recibopedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibopedido',
            name='fk_id_productos',
        ),
        migrations.AddField(
            model_name='recibopedido',
            name='fk_id_productos',
            field=models.ManyToManyField(to='core.producto'),
        ),
    ]
