# Generated by Django 4.1.3 on 2023-06-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_producto_imagenprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fk_id_rol',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='core.rol'),
        ),
    ]
